export { default as Hero } from './hero.png'
export { default as Amazon } from './amazon.png'
export { default as Dribble } from './dribble.png'
export { default as Hubspot } from './hubspot.png'
export { default as Netflix } from './netflix.png'
export { default as Notion } from './notion.png'
export { default as Zoom } from './zoom.png'
